# Generated by Django 2.1.5 on 2023-03-20 17:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 17, 20, 20, 105930, tzinfo=utc)),
        ),
    ]
